### ISSUE TITLE
./adda.py cutpart doesn't work

### ISSUE THREAD

**Issue by tbaumann** [Axford/OpenSCADMachineDesignFramework#5]
Adding a cutpart doesn't work.
```
[tilmanb@zuse-mini-tilman-baumann-name scripts]$ ./adda.py cutpart RightPlate RightPlate
Creating cutpart
Traceback (most recent call last):
  File "./adda.py", line 101, in <module>
    adda(sys.argv[1], sys.argv[2], sys.argv[3] )
  File "./adda.py", line 73, in adda
    with open(outFile,'w') as o:
IOError: [Errno 2] No such file or directory: ''
```

The same works just fine for printed parts
```
[tilmanb@zuse-mini-tilman-baumann-name scripts]$ ./adda.py printedpart RightPlate RightPlate
Creating printedpart
```

**Comment by tbaumann** [comment]
ah, fixed in https://github.com/Axford/OpenSCADMachineDesignFramework/pull/2
